version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:8000
  volumes:
  - ./:/app

 ms:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_root_PASSWORD=saurav
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: